### ISSUE TITLE
Fire Warnings on project item row delete

### ISSUE THREAD

**Issue by joesgit** [GunnJerkens/plumage#48]
If you click on delete for an item, there is no indication that the action has been completed.

**Comment by guitarbeard** [comment]
I'm going to add a delete confirmation modal like the other pages.

**Comment by guitarbeard** [comment]
Actually I think a popover would be better because there is no name for the items so it might be confusing to use a modal and the user might forget which item was clicked on:
![screen shot 2016-04-04 at 11 49 21 am](https://cloud.githubusercontent.com/assets/2850694/14259384/7cc66650-fa5b-11e5-9925-ede636c13dd7.png)
What do yah think @joesgit ?
